[package]
name = "stable-ftp"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.*", features = ["derive"] }
prost = { version = "0.*" }
prost-types = "0.*"
indicatif = { version = "0.*", features = ["unicode-width"]}
rusqlite = { version = "*", features = ["bundled"] }

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
strip = true

[[bin]]
name = "server"
path = "src/server/main.rs"

[[bin]]
name = "client"
path = "src/client/main.rs"

[build-dependencies]
prost-build = "0.13.3"
